[package]
name = "HTTP_Server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
actix-cors = "0.7.0"
actix-files = "0.6"